name: Docker Image CI

on:
  push:
    branches: ["ejercicio1"]
  pull_request:
    branches: ["ejercicio1"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Docker
        uses: docker-practice/actions-setup-docker@master
      # - name: Run Postman Collection v2
      #   run: |
      #     collectionPath="/home/runner/work/DevopsIItests/DevopsIItests"
      #     docker run -v $collectionPath:/etc/newman -t postman/newman:latest run "StorageService.postman_collection.json" --reporters="cli"
      - name: Run artillery tests
        run: |
          artilleryPath="/home/runner/work/DevopsIItests/DevopsIItests/Artillery"
          docker run --rm -v "$artilleryPath:/etc/artillery" artilleryio/artillery:latest run /etc/artillery/api-perf-test.yml
